.TH CAT 1 "October 2023" "User Commands"

.SH NAME
cat \- concatenate and display file content

.SH SYNOPSIS
.B cat
[FILE]...

.SH DESCRIPTION
Displays the content of one or more files to the standard output. If no FILE is provided or if FILE is '-', it reads from the standard input.

.SH OPTIONS
.TP
.B None

.SH EXAMPLES
Display the content of "file.txt":
.B
.PP
.B cat file.txt

Concatenate and display the content of "file1.txt" and "file2.txt":
.B
.PP
.B cat file1.txt file2.txt

.SH AUTHOR
MD ARIF KHAN <arifthehappy@gmail.com>

.SH REPORTING BUGS
Report bugs to: arifthehappy@gmail.com.
