.TH CD 1 "October 2023" "User Commands"

.SH NAME
cd \- change the working directory

.SH SYNOPSIS
.B cd
[DIRECTORY]

.SH DESCRIPTION
Changes the current working directory to the specified DIRECTORY. If no DIRECTORY is provided, it changes to the home directory.

.SH OPTIONS
.TP
.B None

.SH EXAMPLES
Change to the home directory:
.B
.PP
.B cd

Change to the "Documents" directory:
.B
.PP
.B cd Documents

.SH AUTHOR
MD ARIF KHAN <arifthehappy@gmail.com>

.SH REPORTING BUGS
Report bugs to: arifthehappy@gmail.com.
