.TH echo 1 "October 2023" "User Commands"

.SH NAME
echo \- display a line of text

.SH SYNOPSIS
.B echo
[STRING]...

.SH DESCRIPTION
Displays the STRING(s) to the standard output.

.SH OPTIONS
None.

.SH EXAMPLES
Display "Hello, World!":
.B
.PP
.B echo "Hello, World!"

.SH SEE ALSO
.BR printf (1)

.SH AUTHOR
MD ARIF KHAN.

.SH REPORTING BUGS
Report bugs to: arifthehappy@gmail.com.
