.TH ls 1 "October 2023" "User Commands"

.SH NAME
ls \- list files in a directory

.SH SYNOPSIS
.B ls
[\-a] [DIRECTORY]...

.SH DESCRIPTION
List information about the FILEs (the current directory by default).

.SH OPTIONS
.TP
.B \-a
List entries starting with '.' (include hidden files).

.SH EXAMPLES
List files in the current directory:
.B
.PP
.B ls

List all files, including hidden ones, in the "documents" directory:
.B
.PP
.B ls -a documents

.SH SEE ALSO
.BR cd (1)

.SH AUTHOR
MD ARIF KHAN.

.SH REPORTING BUGS
Report bugs to: arifthehappy@gmail.com.
