.TH mkdir 1 "October 2023" "User Commands"

.SH NAME
mkdir \- create directories

.SH SYNOPSIS
.B mkdir
DIRECTORY_NAME

.SH DESCRIPTION
Create a directory with the specified name.

.SH OPTIONS
None

.SH EXAMPLES
Create a directory named "documents":
.B
.PP
.B mkdir documents

.SH SEE ALSO
.BR ls (1)

.SH AUTHOR
MD ARIF KHAN.

.SH REPORTING BUGS
Report bugs to: arifthehappy@gmail.com.
