.TH ps 1 "October 2023" "User Commands"

.SH NAME
ps \- display information about running processes

.SH SYNOPSIS
.B ps

.SH DESCRIPTION
Display information about running processes, including their process ID (PID), terminal, total CPU time, and command.

.SH OPTIONS
None

.SH EXAMPLES
Display information about running processes:
.B
.PP
.B ps

.SH AUTHOR
MD ARIF KHAN.

.SH REPORTING BUGS
Report bugs to: arifthehappy@gmail.com.
