.TH touch 1 "October 2023" "User Commands"

.SH NAME
touch \- create an empty file or update the access and modification times of a file

.SH SYNOPSIS
.B touch
file_name

.SH DESCRIPTION
Create an empty file or update the access and modification times of an existing file.

.SH OPTIONS
None

.SH EXAMPLES
Create an empty file or update the timestamp of an existing file:
.B
.PP
.B touch file_name

.SH SEE ALSO
.BR ls (1)

.SH AUTHOR
MD ARIF KHAN.

.SH REPORTING BUGS
Report bugs to: arifthehappy@gmail.com.
